modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"
showAsDataPack = true

[[mods]]
modId = "wolfgun_music_discs"
version = "${version}"
displayName = "Wolfgun Music Discs"
authors = "satyrnidae (Mod Author, Textures), Wolfgun (Music)"
description = '''
Adds the suite of music from Wolfgun's RUNNING and RUNNING II albums as music disks.
'''
logoFile = "icon.png"
displayURL = "https://wolfgun.bandcamp.com/"

[[dependencies.wolfgun_music_discs]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wolfgun_music_discs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wolfgun_music_discs]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
